### ISSUE TITLE
Clarify Go handling of object oriented programming

### ISSUE THREAD

**Issue by jakerockland** [jakerockland/go-vs-swift#11]

**Comment by jakerockland** [comment]
[/u/daveddev](https://www.reddit.com/r/golang/comments/5jhq6d/go_vs_swift_the_languages_of_the_modern_tech/dbgel0l/?)

> The issue here is that Go is intentionally not OOP heavy. It's OOP-like. While we can clearly define the sharing of behavior through composition, which replaces implementation inheritance through sub-classing, the freedom granted by having interfaces implicitly implemented allows us to also create types that are not bound to class hierarchies and related issues. Interfaces/interface implementation should be most of our focus when reasoning about designs.
> Please consider https://play.golang.org/p/hdEO_DWygr (I hope I stated/coded this all correctly.)

**Comment by jakerockland** [comment]
[/u/planet12](https://www.reddit.com/r/golang/comments/5jhq6d/go_vs_swift_the_languages_of_the_modern_tech/dbgk1d0/?)

> I think the end of section 6 does Go a disservice in the "yes and no" summary. Everyone can be assumed to know what OOP means, but are less likely to understand that Go solves things in a different fashion. Packages, interfaces and composition are surprisingly powerful concepts, and provide ways to make interchangeable parts that can be built into structures then chained together - instead of "is a/implements a" it's more "can be used to do ..."
> 
> I'm still getting my head around it to be honest.

[/u/weberc2](https://www.reddit.com/r/golang/comments/5jhq6d/go_vs_swift_the_languages_of_the_modern_tech/dbh6bjo/?)

>> However, due to its lack of inheritance, attempting to emulate the above Swift example in Go is not straightforward
>
> It's just as straightforward in Go as in Swift. https://play.golang.org/p/tcJNhLy7dy

**Comment by mofeing** [comment]
You should clarify that is an "OOP" language based on Composition, not on Inheritante.

The idea is simple: Go has structs (almost) exactly like C, that is compound data types. Methods are made by binding a function to data type. You can make a method for any data type except primitive types (You can actually make a new data type from a primitive type and bind methods to it).

Instead of inhereting attributes, methods, properties... whatever from a super-class, you create a field inside the struct whose class is the class you want to inherit. That is Composition.

Furthermore, Go supports Anonymous Composition: If you don't name the field you are "composing", the struct can access its methods and fields directly.

[Anonymous fields in structs - like object composition](https://golangtutorials.blogspot.com.es/2011/06/anonymous-fields-in-structs-like-object.html)
[Using Anonymous Field to Extend Structs in Go](http://dennissuratna.com/using-anonymous-field-to-extend-in-go/)

The idea is totally the opposite to the Inheritance Hierarchy. Instead of doing abstractions and specify an Object by going down on the hierarchy, you build "compound" a class with objects.

For example, imagine we want to create a Car class. Inheritance would make us to make a TerrestrialVehicle super-class, a MotorizedVehicle super-super-class and Vehicle super-super-super-class. With Composition, we would only have to create the Engine, Radio, Seat and a large etcetera, "classes" and the Car "class" would wrap them.

The problem with Inheritance is that in a big project, you end up with a lot of Abstract Classes that do not serve for nothing but to relate different classes. Composition solves this problem.

I find it too more modular, which I really like, but it has its limitations.
